name: Setup Nginx

on:
  push:
    branches:
      - main

jobs:
  setup-nginx:
    runs-on: [self-hosted, devops-dev]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx

    - name: Start and enable Nginx
      run: |
        sudo systemctl start nginx
        sudo systemctl enable nginx

    - name: Verify Nginx status
      run: |
        sudo systemctl status nginx

