name: Setup WordPress on node2

  #on:
  #  push:
  #    branches:
  #      - main

on:
  workflow_run:
    workflows: ["Setup LAMP Stack on node2"]
    types:
      - completed

jobs:
  setup-lamp:
    runs-on: [self-hosted, devops]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run LAMP setup script
      env:
        SUDO_PASSWORD: ${{ secrets.sudo_pass }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_USER: ${{ vars.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        SERVER_NAME: ${{ secrets.SERVER_NAME }}
        SERVER_ALIAS: ${{ secrets.SERVER_ALIAS }}
      run: |
        chmod +x ./scripts/install_wordpress.sh
        echo "$SUDO_PASSWORD" | sudo -S ./scripts/install_wordpress.sh $DB_NAME $DB_USER $DB_PASS $SERVER_NAME $SERVER_ALIAS

