name: Uninstall LAMP Stack and WordPress on node2

on:
  workflow_run:
    workflows: ["Uninstall Nginx on node1"]
    types:
      - completed

jobs:
  uninstall-lamp-wordpress:
    runs-on: [self-hosted, devops]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run LAMP and WordPress uninstall script
      env:
        SUDO_PASSWORD: ${{ secrets.sudo_pass }}
      run: |
        chmod +x ./scripts/uninstall_lamp.sh
        echo "${SUDO_PASSWORD}" | sudo -S ./scripts/uninstall_lamp.sh
